### ISSUE TITLE
mod not showing for some uses

### ISSUE THREAD

**Issue by The-Repo-Club** [terminalforlife/Extra#16] opened 2021-12-30 12:35 UTC
![image](https://user-images.githubusercontent.com/9284733/147752447-896e403c-d306-4c1f-a716-6669b1e3f2e9.png)

**Comment by terminalforlife** [comment] 2021-12-30 16:03
Can I see your configuration file?

**Comment by The-Repo-Club** [comment] 2021-12-30 17:05
[Config](https://raw.githubusercontent.com/endeavouros-team/endeavouros-i3wm-setup/main/.config/i3/config) i believe this is the config in question im just asking the user if they uses there default

**Comment by terminalforlife** [comment] 2021-12-31 16:45
What do you mean by _"im just asking the user if they uses there default"_?

**Comment by The-Repo-Club** [comment] 2021-12-31 18:46
Luke didnt wanna file the report himself so i was asking if he was using defaults

**Comment by terminalforlife** [comment] 2021-12-31 21:36
Who's Luke? I'm confused. Lol Are you reporting the bug on behalf of another user?

**Comment by The-Repo-Club** [comment] 2022-01-01 02:53
Yes I'm reporting the bug on behalf of a use that doesn't use GitHub sorry for the confusion

**Comment by terminalforlife** [comment] 2022-01-01 09:59
Should be fixed now. Let Luke know he should update CSI3, and that it should be working for him.

**Comment by terminalforlife** [comment] 2022-01-01 10:06
Should be fixed now. Let Luke know he should update CSI3, and that it should be working for him. Please let me know if it works, so I can close the issue. Be sure to let Luke know that lines split up by `\` is not currently (if ever) supported in CSI3, due to the unnecessary complexity it'd (likely) introduce.

**Comment by sirlucidae** [comment] 2022-01-03 09:34
@terminalforlife 
Hello! I can confirm CSI3 is fixed now with my config. Thank you.

![Screenshot_2022-01-03_19-30-17](https://user-images.githubusercontent.com/93426700/147916256-e33d77d4-34d3-4610-ad24-94a9b5515d84.png)

**Comment by terminalforlife** [comment] 2022-01-03 11:02
You're welcome, and thank you for letting me know!

**Closed** 2022-01-03 11:01 UTC
Labels: Bug Report
